[INFO   ] Logger: Record log in /storage/emulated/0/Nimer_Project /.kivy/logs/kivy_25-02-25_6.txt
[INFO   ] Kivy: v2.2.1
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.11.4 (main, Sep 30 2023, 10:54:38) [GCC 11.4.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
[INFO   ] Logger: Purge log fired. Processing...
[INFO   ] Logger: Purge finished!
[INFO   ] Factory: 190 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.2 v1.r34p0-01eac0.647697edc2c1e52dec0a7e587b626ab2'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-G57'>
[INFO   ] GL: OpenGL parsed version: 3, 2
[INFO   ] GL: Texture max size <16383>
[INFO   ] GL: Texture max units <128>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Camera: Provider: android
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/Nimer_Project /main.py", line 20, in <module>
[WARNING] stderr:     request_permissions([Permission.CAMERA])
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/android/permissions.py", line 598, in request_permissions
[WARNING] stderr:     _RequestPermissionsManager.request_permissions(permissions, callback)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/android/permissions.py", line 538, in request_permissions
[WARNING] stderr:     cls.register_callback()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/android/permissions.py", line 514, in register_callback
[WARNING] stderr:     cls._java_callback = _onRequestPermissionsCallback(cls.python_callback)
[WARNING] stderr:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/android/permissions.py", line 467, in __init__
[WARNING] stderr:     super().__init__()
[WARNING] stderr:   File "jnius/jnius_proxy.pxi", line 28, in jnius.jnius.PythonJavaClass.__init__
[WARNING] stderr:   File "jnius/jnius_proxy.pxi", line 34, in jnius.jnius.PythonJavaClass._init_j_self_ptr
[WARNING] stderr:   File "jnius/jnius_proxy.pxi", line 180, in jnius.jnius.create_proxy_instance
[WARNING] stderr:   File "jnius/jnius_export_class.pxi", line 877, in jnius.jnius.JavaMethod.__call__
[WARNING] stderr:   File "jnius/jnius_export_class.pxi", line 1043, in jnius.jnius.JavaMethod.call_staticmethod
[WARNING] stderr:   File "jnius/jnius_utils.pxi", line 79, in jnius.jnius.check_exception
[WARNING] stderr: jnius.jnius.JavaException: JVM exception occurred: interface org.kivy.android.PythonActivity$PermissionsCallback is not visible from class loader java.lang.IllegalArgumentException
